"""add_file_uploads_table

Revision ID: 43601fc5956f
Revises: 21b0095185da
Create Date: 2025-12-10 20:18:06.854785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43601fc5956f'
down_revision: Union[str, Sequence[str], None] = '21b0095185da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'file_uploads' in inspector.get_table_names():
        print("Table file_uploads already exists, skipping creation")
        # Still need to drop the constraint if it exists
        try:
            op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
        except:
            pass
        return
    
    # Create enum type if it doesn't exist (using raw SQL to avoid SQLAlchemy issues)
    op.execute("DO $$ BEGIN CREATE TYPE fileuploadstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Use String type with CHECK constraint instead of Enum to avoid SQLAlchemy enum creation issues
    op.create_table('file_uploads',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_file_uploads_upload_id'), 'file_uploads', ['upload_id'], unique=False)
    
    # Add CHECK constraint for status values
    op.execute("ALTER TABLE file_uploads ADD CONSTRAINT file_uploads_status_check CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))")
    
    # Change status column to use enum type
    op.execute("ALTER TABLE file_uploads ALTER COLUMN status TYPE fileuploadstatus USING status::fileuploadstatus")
    
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Drop table if it exists
    if 'file_uploads' in inspector.get_table_names():
        op.drop_index(op.f('ix_file_uploads_upload_id'), table_name='file_uploads')
        op.drop_table('file_uploads')
    
    # Recreate constraint if users table exists
    if 'users' in inspector.get_table_names():
        try:
            op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
        except:
            pass
    # ### end Alembic commands ###
